
version: '3'
services:
  app:
    build:
      context: ./docker
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    user: "1000"
    command: ["php", "-S", "0.0.0.0:8000", "-t", "src/"]